CREATE DATABASE mydb;

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL, 
  password VARCHAR(255) NOT NULL, 
  email_address VARCHAR(255) UNIQUE,
  contact_number VARCHAR(20) NOT NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

