CREATE DATABASE mydb;

CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50), password VARCHAR(255), email_address VARCHAR(255), contact_number VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);