CREATE DATABASE mydb;

CREATE TABLE admin (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, 
    email_address VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(20),          
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL, 
  password VARCHAR(255) NOT NULL, 
  email_address VARCHAR(255) UNIQUE,
  contact_number VARCHAR(20) NOT NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

